"use client";

import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#fafafa] selection:bg-purple-100 selection:text-purple-900">
      <Nav />

      <section className="pt-48 pb-32 px-6 md:px-10">
        <div className="max-w-3xl mx-auto bg-white p-10 md:p-16 rounded-[40px] shadow-sm border border-gray-100">
          <div className="mb-12">
            <h1 className="text-4xl font-medium tracking-tight mb-4">Terms of Service</h1>
            <p className="text-gray-500 text-sm font-medium">Effective Date: May 15, 2026 | MetaMate Stealth Beta (v0.1)</p>
          </div>

          <div className="space-y-10 text-gray-600 leading-relaxed text-[15px]">
            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p>
                By applying for, accessing, or using the MetaMate stealth beta ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not access or use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4">2. Experimental Platform Disclaimer</h2>
              <p className="font-medium text-gray-900 mb-2">The Service is currently in an experimental "Stealth Beta" phase.</p>
              <p>
                You acknowledge and agree that the Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind. The platform may contain bugs, errors, or inaccuracies that could cause failures, corruption, or loss of data and information. We strongly advise against relying on MetaMate for mission-critical business, financial, or personal tasks during this phase.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4">3. Beta Limitations & Availability</h2>
              <p>
                Access to the Service is granted at our sole discretion. We reserve the right to limit, suspend, or terminate your access to the Service at any time, for any reason, without notice. The availability of the Service is not guaranteed, and we may experience extended periods of downtime as we upgrade our core infrastructure and AI orchestration layers.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4">4. AI Disclaimers</h2>
              <p>
                MetaMate utilizes advanced generative AI and autonomous orchestration protocols. You understand that:
              </p>
              <ul className="list-disc pl-5 space-y-2 mt-4">
                <li>AI output is probabilistic and may produce inaccurate, inappropriate, or unintended responses (often referred to as "hallucinations").</li>
                <li>You are solely responsible for verifying the accuracy and appropriateness of any action taken or output generated by your MetaMate.</li>
                <li>MetaMate is not responsible for any social, financial, or legal consequences resulting from the autonomous actions of your digital identity.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4">5. Acceptable Use Policy</h2>
              <p className="mb-4">
                You agree not to use the Service to:
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Create MetaMates that impersonate real individuals without their explicit, cryptographic consent.</li>
                <li>Deploy autonomous agents designed to harass, defraud, spam, or maliciously manipulate online or real-world systems.</li>
                <li>Reverse-engineer, decompile, or extract the proprietary models or memory vectors of the Service.</li>
              </ul>
              <p className="mt-4">
                Violation of the Acceptable Use Policy will result in immediate termination of beta access and permanent banning from the ecosystem.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4">6. Intellectual Property</h2>
              <p>
                MetaMate retains all rights, title, and interest in and to the Service, including all underlying software, AI models, algorithms, and branding. You retain ownership of the baseline data you input to train your MetaMate, subject to the license granted to us in our Privacy Policy to operate the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4">7. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, MetaMate and its founders, employees, and partners shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 mb-4">8. Contact</h2>
              <p>
                For legal inquiries regarding these Terms, please contact <a href="mailto:legal@metamate.com" className="text-purple-600 font-bold hover:underline">legal@metamate.com</a>.
              </p>
            </section>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
